|----------------------------------------------|
|------------ configuration files -------------|
|----------------------------------------------|
| Formats:                                     |
| 0 - DDalphaAMG                               |
| 1 - LIME                                     |
|----------------------------------------------|

configuration: /beegfs/jimenezmerchan/configs/qcdsf.632.01000.mg2
format: 0

|----------------------------------------------|
|----------- Select right hand side -----------|
|----------------------------------------------|
| 0 - ones                                     |
| 1 - first unit vector                        |
| 2 - random                                   |
|----------------------------------------------|
right hand side: 0

|----------------------------------------------|
|--- Information about the lattice geometry ---|
|--- fine grid = depth 0 ----------------------|
|----------------------------------------------|
| ordering = [ T, Z, Y, X ]                    |
|----------------------------------------------|
| ----- antiperiodic boundary conditions ------|
| 0 - periodic (1,1,1,1)                       |
| 1 - antiperiodic in time (-1,1,1,1)          |
|----------------------------------------------|
antiperiodic boundary conditions: 0
number of levels: 3
number of openmp threads: 1

|----------------------------------------------|
|----- Decide whether to do probing or not ----|
|----------------------------------------------|
| 0 - probing is not performed                 |
| 1 - probing is performed                     |
|----------------------------------------------|
probing selection: 1
timeslice coloring: 3   // 4 - 4D coloring,  3 - 3D coloring (on a timeslice)
coloring distance: 40

dilution: 12 // 1: no dilution, 2: partial spin dilution, 3: color dilution, 4: complete spin dilution, 12: spin-color dilution

Decide which grids have to be colored. E.g. a value of 2 means that the first 2 grids are colored while the remaining are not
coloring: 1

|--- depth 0 ----------------------------------|
d0 global lattice: 64 32 32 32
d0 local lattice:   8  8  8 16
d0 block lattice:   4  4  4  4
d0 preconditioner cycles: 1
d0 post smooth iter: 3
d0 block iter: 4
d0 test vectors: 28  //--use 28
d0 setup iter: 5   //--use 7

d0 trace op type: 19
fine grid polyprec enabled: 1
fine grid polyprec_nrhs: 1
fine grid polyprec_d: 41		//color-distance >= pol_d - 1
fine grid polyprec_splitting: 0
fine grid polyprec_omega: 1.0

hpe op trace method: 4
hpe order: 41
delta m: 0.0 // For frequency splitting

d0 trace max iters: 200
d0 trace min iters: 200

d0 trace deflation type: 0   // 0 is difference, 1 is non-difference, 2 is split(intermediate) , 3 is no deflation
d0 trace deflation nr vectors: 32   //---24
d0 trace powerit solver tol: 1.0e-6
d0 trace powerit cycles: 5
d0 trace powerit spectrum type: 0   // 0 is EVs, 1 is SVs

|--- depth 1 ----------------------------------|
d1 global lattice: 16 8 8 8
d1 local lattice:   2 2 2 4
d1 block lattice:   2 2 2 2
d1 preconditioner cycles: 1
d1 post smooth iter: 3
d1 block iter: 4
d1 test vectors: 28
d1 setup iter: 4

d1 trace max iters: 128
d1 trace min iters: 128


d1 trace deflation type: 0   // 0 is difference, 1 is non-difference, 2 is split(intermediate) , 3 is no deflation
d1 trace deflation nr vectors: 12
d1 trace powerit solver tol: 1.0e-8
d1 trace powerit cycles: 5
d1 trace powerit spectrum type: 0   // 0 is EVs, 1 is SVs

|--- depth 1 ----------------------------------|
d2 global lattice:  8 4 4 4
d2 local lattice:   1 1 1 2

d2 trace max iters: 128
d2 trace min iters: 128

d2 trace deflation type: 0   // 0 is difference, 1 is non-difference, 2 is split(intermediate) , 3 is no deflation
d2 trace deflation nr vectors: 12
d2 trace powerit solver tol: 1.0e-9
d2 trace powerit cycles: 15
d2 trace powerit spectrum type: 0   // 0 is EVs, 1 is SVs

|----------------------------------------------|
|-------------- Wilson operator ---------------|
|----------------------------------------------|


m0: -0.332159624413


csw: 1.9192

  mux: 0.0001
  mu: 0.0
  setup mux: 0.0001
  setup mu: 0.0
  mu odd shift: 0.0
  mu even shift: 0.0
  epsbar: 0.00
  epsbar odd shift: 0.0
  epsbar even shift: 0.0
addDownPropagator: 0

tolerance for relative residual: 1E-10
iterations between restarts: 10
maximum of restarts: 50

coarse grid tolerance: 1.0E-1
coarse grid iterations: 80
coarse grid restarts: 5

kcycle: 1
kcycle length: 30
kcycle restarts: 10
kcycle tolerance: 1E-1

mu coarsest: 0.0001

coarse grid gcrodr_upd_itrs_setup: 0
coarse grid gcrodr_upd_itrs_solve: 0

coarse grid gcrodr_k: 25
coarse grid gcrodr_k_setup: 25
coarse grid gcrodr_k_solve: 25

coarse grid polyprec_d: 5
coarse grid polyprec_d_setup: 5
coarse grid polyprec_d_solve: 5


#general_param
print mode: 1
method: 4
interpolation: 2
mixed precision: 0
 randomize test vectors: 0               // initialize random number generator with time(0) ? 0=no/1=yes
odd even preconditioning: 1

// for further information, please read the user documentation in doc/
// developers version of an input file in sample_devel.ini
