#!/bin/bash
#SBATCH --job-name=3Dplain-colored
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=64
#SBATCH --cpus-per-task=1
#SBATCH --output=result
#SBATCH --error=err_file
#SBATCH --time=24:59:00
#SBATCH --mail-type=ALL           # Mail events (NONE, BEGIN, END, FAIL, ALL)

export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}
module load 2023a
module load GCC/12.3.0
module load OpenMPI/4.1.5

make clean
make -f Makefile -j 32

. run -i "3d-8to4-plain.ini"
date
