|----------------------------------------------|
|------------ configuration files -------------|
|----------------------------------------------|
| Formats:                                     |
| 0 - DDalphaAMG                               |
| 1 - LIME                                     |
|----------------------------------------------|

configuration: /beegfs/papace/configs/qcdsf.632.01000.mg2
format: 0

|----------------------------------------------|
|----------- Select right hand side -----------|
|----------------------------------------------|
| 0 - ones                                     |
| 1 - first unit vector                        |
| 2 - random                                   |
|----------------------------------------------|
right hand side: 0

|----------------------------------------------|
|--- Information about the lattice geometry ---|
|--- fine grid = depth 0 ----------------------|
|----------------------------------------------|
| ordering = [ T, Z, Y, X ]                    |
|----------------------------------------------|
| ----- antiperiodic boundary conditions ------|
| 0 - periodic (1,1,1,1)                       |
| 1 - antiperiodic in time (-1,1,1,1)          |
|----------------------------------------------|
antiperiodic boundary conditions: 0
number of levels: 3
number of openmp threads: 1

|----------------------------------------------|
|----- Decide whether to do probing or not ----|
|----------------------------------------------|
| 0 - probing is not performed                 |
| 1 - probing is performed                     |
|----------------------------------------------|
probing selection: 2     // 0 - no probing, 1 - classical probing, 2 - hierarchical probing
coloring distance: 1   // For classical probing
hierarchy step: 4     // k value for hierarchical probing
interrupt: 1         // For hierarchical probing -> if 1 then stop num colors at num hadamard
num hadamard: 2162

dilution: 12 // 1: no dilution, 2: partial spin dilution, 3: color dilution, 4: complete spin dilution, 12: spin-color dilution

Decide which grids have to be colored. E.g. a value of 2 means that the first 2 grids are colored while the remaining are not
colored grids: 1

gamma index: 0 //Decide what Gamma Dirac matrix to use --> currently works only for operation type 2

|--- depth 0 ----------------------------------|
d0 global lattice: 64 32 32 32
d0 local lattice:   8  8  8 16
d0 block lattice:   4  4  4  4
d0 preconditioner cycles: 1
d0 post smooth iter: 3
d0 block iter: 4
d0 test vectors: 28  //--use 28

d0 default setup: 1
d0 eigenres tol: 1E-8
d0 interpolation vectors: 0  //0 is D, 1 is Q

interpolation: 2                                //4: read from file 2: no-read
store test vectors: 0                           // yes / no
test vector io file name: test_vectors.tv
number store test vectors: 20


d0 trace op type: 2  // 1 is disc-mlmc, 2 is disc-plain
d0 trace max iters: 5
d0 trace min iters: 5


|--- depth 1 ----------------------------------|
d1 global lattice: 16 8 8 8
d1 local lattice:   2 2 2 4
d1 block lattice:   2 2 2 2
d1 preconditioner cycles: 1
d1 post smooth iter: 3
d1 block iter: 4
d1 test vectors: 28
d1 setup iter: 4

d1 trace max iters: 250
d1 trace min iters: 250

|--- depth 1 ----------------------------------|
d2 global lattice:  8 4 4 4
d2 local lattice:   1 1 1 2

d2 trace max iters: 1000
d2 trace min iters: 1000

|----------------------------------------------|
|-------------- Wilson operator ---------------|
|----------------------------------------------|


m0: -0.332159624413


csw: 1.9192

  mux: 0.0001
  mu: 0.0
  setup mux: 0.0001
  setup mu: 0.0
  mu odd shift: 0.0
  mu even shift: 0.0
  epsbar: 0.00
  epsbar odd shift: 0.0
  epsbar even shift: 0.0
addDownPropagator: 0

tolerance for relative residual: 1E-12
iterations between restarts: 10
maximum of restarts: 50

coarse grid tolerance: 1.0E-1
coarse grid iterations: 80
coarse grid restarts: 5

kcycle: 1
kcycle length: 30
kcycle restarts: 10
kcycle tolerance: 1E-1

mu coarsest: 0.0001

coarse grid gcrodr_upd_itrs_setup: 0
coarse grid gcrodr_upd_itrs_solve: 0

coarse grid gcrodr_k: 25
coarse grid gcrodr_k_setup: 25
coarse grid gcrodr_k_solve: 25

coarse grid polyprec_d: 5
coarse grid polyprec_d_setup: 5
coarse grid polyprec_d_solve: 5


#general_param
print mode: 1
method: 4
mixed precision: 0
 randomize test vectors: 0               // initialize random number generator with time(0) ? 0=no/1=yes
odd even preconditioning: 1

// for further information, please read the user documentation in doc/
// developers version of an input file in sample_devel.ini
