#!/bin/bash
#SBATCH --job-name=IV-hpe-2
#SBATCH --nodes=16
#SBATCH --ntasks-per-node=16
#SBATCH --cpus-per-task=1
#SBATCH --output=result-IV-hpe-2
#SBATCH --error=err-IV-hpe-2
#SBATCH --time=23:59:00
#SBATCH --mail-type=ALL          # Mail events (NONE, BEGIN, END, FAIL, ALL)

module purge

module load 2023a

module load GCC/12.3.0

module load OpenMPI/4.1.5



export OMP_NUM_THREADS=${SLURM_CPUS_PER_TASK}



. run -i "IV_hpe_2.ini"
date
